### ISSUE TITLE
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 454 pos 7: '_ticker != null': AnimationController.forward() called after AnimationController.dispose()

### ISSUE THREAD

**Issue by BunnyBuddy** [BrunoJurkovic/flip_card#92]
I am using 2 FlipCards and they have to flip every 5 seconds, but the moment I added the second flip card, every time I land on the screen it throws this error but keeps working okay.

## ERROR:

```
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 454 pos 7: '_ticker != null': AnimationController.forward() called after AnimationController.dispose()
flutter: AnimationController methods should not be used after calling dispose., STACK TRACE: #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
flutter: #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
flutter: #2      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:454:7)
flutter: #3      FlipCardState.toggleCard (package:flip_card/flip_card.dart:181:45)
flutter: #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:393:39)
flutter: #5      _rootRun (dart:async/zone.dart:1418:47)
flutter: #6      _CustomZone.run (dart:async/zone.dart:1328:19)
flutter: #7      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
flutter: #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
flutter: #9      _rootRun (dart:async/zone.dart:1426:13)
flutter: #10     _CustomZone.run (dart:async/zone.dart:1328:19)
flutter: #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
flutter: #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
flutter: #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
flutter: #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
flutter: #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
flutter:
```

## Steps to Reproduce
This is my current code, (using GetX for state management)

 ```
 var flipController = FlipCardController().obs;
  var monthlyFlipCon = FlipCardController().obs;
  
    @override
  void dispose() {
    if (flipController.value.state != null) {
      if (flipController.value.state.mounted) {
        flipController.value.state.dispose();
      }
    }
    if (monthlyFlipCon.value.state != null) {
      if (monthlyFlipCon.value.state.mounted) {
        monthlyFlipCon.value.state.dispose();
      }
    }
    super.dispose();
  }

// in the build method
FlipCard(
                                      controller: flipController.value,
                                      direction: FlipDirection.VERTICAL,
                                      side: CardSide.FRONT,
                                      flipOnTouch: false,
                                      autoFlipDuration: const Duration(seconds: 5),
                                      onFlipDone: (val) {
                                        Future.delayed(Duration(seconds: 10), () {
                                          flipController.value.state.mounted ? flipController.value.state.toggleCard() : null;
                                        });
                                      },
                                      front: CountDownTimer(
                                        secondsRemaining: productController.seconds.value,
                                        timeBoxHeight: 20.h,
                                        timeBoxWidth: 20.w,
                                        timerTextStyle: ThemeStyles.NORMAL_STYLE_LIGHT.copyWith(
                                          color: Constant.backgroundColor,
                                          fontSize: 12.sp,
                                        ),
                                        whenTimeExpires: () {
                                          productController.seconds.value = 0;
                                        },
                                        countDownTimerStyle: ThemeStyles.HEADING_STYLE_BOLD.copyWith(color: Constant.backgroundColor),
                                        prefixText: "",
                                      ),
                                      back: Text(
                                        'Limited time offer',
                                        style: ThemeStyles.NORMAL_STYLE_LIGHT.copyWith(fontSize: 14.sp, color: Constant.backgroundColor),
                                      ),
                                    ),
                                    
                                    FlipCard(
                                      controller: monthlyFlipCon.value,
                                      direction: FlipDirection.VERTICAL,
                                      side: CardSide.FRONT,
                                      flipOnTouch: false,
                                      autoFlipDuration: const Duration(seconds: 5),
                                      onFlipDone: (val) {
                                        Future.delayed(Duration(seconds: 10), () {
                                          monthlyFlipCon.value.state.mounted ? monthlyFlipCon.value.state.toggleCard() : null;
                                        });
                                      },
                                      front: CountDownTimer(
                                        secondsRemaining: productController.remainingSeconds.value,
                                        timeBoxHeight: 20.h,
                                        timeBoxWidth: 20.w,
                                        timerTextStyle: ThemeStyles.NORMAL_STYLE_LIGHT.copyWith(
                                          color: Constant.backgroundColor,
                                          fontSize: 12.sp,
                                        ),
                                        whenTimeExpires: () {
                                          productController.remainingSeconds.value = 0;
                                        },
                                        countDownTimerStyle: ThemeStyles.HEADING_STYLE_BOLD.copyWith(color: Constant.backgroundColor),
                                        prefixText: "",
                                      ),
                                      back: Text(
                                        'Limited time offer',
                                        style: ThemeStyles.NORMAL_STYLE_LIGHT.copyWith(fontSize: 14.sp, color: Constant.backgroundColor),
                                      ),
                                    ),
```

**Comment by ciriousjoker** [comment]
Two things:
1. Imo, getx is a huge noob trap because while it makes many things more convenient than doing it the "correct" way, it also hides a lot of the internal workings and leads to hard to fix bugs down the line. I've experienced this myself with my early projects, but also heard this independently from many devs whose opinion I highly value.
2. What is obs? Why aren't you just creating FlipCardControllers regularly? Is obs some sort of getx magic? If so, I have no idea how to help you aside from pointing towards the readme and try to follow the example as closely as possible

**Comment by BunnyBuddy** [comment]
@ciriousjoker 
Its just making the variable/controller or whatever observable and instead of calling setState() I can just wrap the widget, with that particular variable, in Obx() and it'll listen for changes. 
It's kinda similar to setstate (but instead of rebuilding the entire widget tree It just updates that particular widget which is performance wise better believe it or not).
I've tried it without GetX as well and it does the same thing so I am pretty sure a different state management is not the issue here.
Cheers.

**Comment by ciriousjoker** [comment]
@BunnyBuddy 
Ah ok. I'm not convinced that obx can bypass the regular flutter rendering process of laying out the whole subtree of widgets again on every state while reusing unchanged stuff, but I haven't done any benchmarks or looked into it yet.

Either way, my guess is that without obx magic it should work.

**Comment by BunnyBuddy** [comment]
Okay, I've narrowed down the problem.

It has nothing to do with Obx or SetState. 
The issue so far is, if there's a widget being shown to the user at the start of the screen instead of FlipCard and then after a while we show our flipcard, it throws this exception.
 
To my understanding its working like: 

1. The flip card controller is initialised, 
2. If the autoflipduration is given, It keeps the future instead of disposing/pausing the animation controller for some reason while the loader is being shown (or any other widget in place of flip card like maybe a shimmer loader).
3. Then as soon as the FlipCard gets back on screen and the future is ran(according to autoflipduration) it throws this error of animation controller being null.

Maybe if we add ? instead of ! after **controller** in flip_card.dart, at line,

`final animation = isFront ? controller?.forward() : controller?.reverse();`

it may solve this issue. I haven't tested it.

**Comment by ciriousjoker** [comment]
You can easily test your fix by simply editing the package code (Ctrl + click) so vs code opens the packages internal code. There you can edit anything you like and test it out. To revert, just flutter clean and pub get again.

If you manage to figure it out, feel free to open a PR. I can review and merge stuff, but I don't have the time to reread the whole code of this package to fix bugs.

**Comment by BunnyBuddy** [comment]
Yup, the issue is resolved when I add a **mounted** check before calling the forward() method. This new toggleCard() method resolves the issue and keeps the functionality as is.
Thankyou for your time and this awesome package. 
Cheers.

```
  Future<void> toggleCard() async {
        if(!mounted) return; // just needed this line in this method, in 83 dev branch this has already been implemented but its not in the files on pub dev
    widget.onFlip?.call();

    final isFrontBefore = isFront;
    controller!.duration = Duration(milliseconds: widget.speed);

    final animation = isFront ? controller!.forward() : controller!.reverse();
    animation.whenComplete(() {
      if (widget.onFlipDone != null) widget.onFlipDone!(isFront);
      if (!mounted) return;
      setState(() => isFront = !isFrontBefore);
    });
  }
```

**Comment by ciriousjoker** [comment]
Nice! Can you open a PR?
Edit: nevermind got it
